export const AppEvents = {
  TENDER_CREATED: 'tender.created',
  TENDER_UPDATED: 'tender.updated',
  TENDER_ASSIGNED: 'tender.assigned',
  TENDER_STATUS_CHANGED: 'tender.status_changed',
  TENDER_DEADLINE_SOON: 'tender.deadline_soon',
  TENDER_DEADLINE_APPROACHING: 'tender.deadline_approaching',
  TENDER_DEADLINE_EXCEEDED: 'tender.deadline_exceeded',
  TENDER_APPROVAL_REQUESTED: 'tender.approval_requested',
  TENDER_APPROVED: 'tender.approved',
  TENDER_REJECTED: 'tender.rejected',
  TENDER_PREPARATION_STARTED: 'tender.preparation_started',
  TENDER_PQ_SUBMITTED: 'tender.pq_submitted',
  TENDER_PQ_QUALIFIED: 'tender.pq_qualified',
  TENDER_SUBMITTED: 'tender.submitted',
  TENDER_PORTAL_ISSUE_CREATED: 'tender.portal_issue_created',
  TENDER_PORTAL_ISSUE_ESCALATED: 'tender.portal_issue_escalated',
  TENDER_PORTAL_ISSUE_RESOLVED: 'tender.portal_issue_resolved',
  TENDER_WON: 'tender.won',
  TENDER_LOST: 'tender.lost',
  TENDER_CANCELLED: 'tender.cancelled',
  TENDER_ON_HOLD: 'tender.on_hold',

  EXPENSE_SUBMITTED: 'expense.submitted',
  EXPENSE_MANAGER_APPROVED: 'expense.manager_approved',
  EXPENSE_PROCESSED: 'expense.processed',
  EXPENSE_REJECTED: 'expense.rejected',

  TASK_ASSIGNED: 'task.assigned',
  TASK_BLOCKED: 'task.blocked',
  TASK_OVERDUE: 'task.overdue',

  VISIT_CANCELLED: 'visit.cancelled',
  VISIT_RESCHEDULED: 'visit.rescheduled',
  VISIT_MODIFIED: 'visit.modified',
  VISIT_COMPLETED: 'visit.completed',
  VISIT_ALSO_MEET: 'visit.also_meet',
  TRIP_CREATED: 'trip.created',
  TRIP_VISIT_ADDED: 'trip.visit_added',

  SERVICE_CREATED: 'service.created',
  SERVICE_RESOLVED: 'service.resolved',

  DEMO_REQUESTED: 'demo.requested',
  DEMO_TEAM_ASSIGNED: 'demo.team_assigned',
  DEMO_EQUIPMENT_RESERVED: 'demo.equipment_reserved',
  DEMO_CONFIRMED: 'demo.confirmed',
  DEMO_RESCHEDULED: 'demo.rescheduled',
  DEMO_CANCELLED: 'demo.cancelled',
  DEMO_COMPLETED: 'demo.completed',

  PROPOSAL_CREATED: 'proposal.created',
  PROPOSAL_STATUS_CHANGED: 'proposal.status_changed',
  PROPOSAL_REVIEW_REQUESTED: 'proposal.review_requested',
  PROPOSAL_APPROVED: 'proposal.approved',
  PROPOSAL_SENT: 'proposal.sent',
  PROPOSAL_FOLLOWUP_LOGGED: 'proposal.followup_logged',
  PROPOSAL_OUTCOME_RECORDED: 'proposal.outcome_recorded',
  PROPOSAL_OVERDUE_FOLLOWUP: 'proposal.overdue_followup',
  PROPOSAL_INACTIVITY_WARNING: 'proposal.inactivity_warning',

  // Module 1: Leads, Organisations, Interactions & Follow-ups
  LEAD_CREATED: 'lead.created',
  LEAD_UPDATED: 'lead.updated',
  LEAD_RE_APPROACHED: 'lead.re_approached',
  LEAD_ASSIGNED: 'lead.assigned',
  LEAD_STATUS_CHANGED: 'lead.status_changed',
  LEAD_CONVERTED: 'lead.converted',
  LEAD_LOST: 'lead.lost',
  INTERACTION_CREATED: 'interaction.created',
  INTERACTION_UPDATED: 'interaction.updated',
  FOLLOWUP_CREATED: 'followup.created',
  FOLLOWUP_COMPLETED: 'followup.completed',
  FOLLOWUP_OVERDUE: 'followup.overdue',
} as const;
